In [1]:
"""
##1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it 
enhance Python's capabilities for numerical operations
Ans. 
NumPy (Numerical Python) is an open source Python library that's widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray , and a large library of functions that operate efficiently on these data structures.
Its ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries.
NumPy arrays provide a significant speed advantage over traditional lists. This is because NumPy is built in C and uses optimized, pre-compiled code for numerical operations. This allows for vectorization, which means operations are applied to all elements in an array without the need for explicit loops in Python.

##2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the 
other?
Ans. 

Average is recommended for calculation for terms that are close to each other while mean is recommended for calculation for terms that differ from each other and are not closely related.

Average is defined as sum of terms on which we need to perform average divided by the total count of the number of terms.
Average is recommended for calculation for terms that are close to each other.
Average refers to be arithmetic mean of a given value set.

Mean is the smallest term of all the given terms summed up with the largest term and then the result is divided by 2. as well as dividing sum of terms by total number of terms
Mean is recommended for calculation for terms that differ from each other and are not closely related.
Mean can be referred for arithmetic, geometric or harmonic mean of a given value set.

##3
Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D 
arrays.

Ans.Using flip() function to Reverse a Numpy array
the numpy. flipud() function is used to reverse the order of elements along the first axis (up-down direction) of the array
1D= [1,2,3,4]
2d= [[1,2,3],[2,4,5]]
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types 
in memory management and performance

Using dtypes attribute we can determine the data type of emelements in Numpy
ata types are crucial in efficient memory allocation and management within programming. Each data type requires a different amount of memory, and understanding this is key to writing efficient programs, especially in environments with limited memory resources.
5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists
Ans
An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape , which is a tuple of N non-negative integers that specify the sizes of each dimension.
6.. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
Ans. NumPy arrays provide a significant speed advantage over traditional lists. This is because NumPy is built in C and uses optimized, pre-compiled code for numerical operations. This allows for vectorization, which means operations are applied to all elements in an array without the need for explicit loops in Python
7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and 
output.
Ans.
hstack is used to stack elements in the horizontal direction. stack is used to stack elements in the vertical or horizontal direction.
"""

"\n##1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it \nenhance Python's capabilities for numerical operations\nAns. \nNumPy (Numerical Python) is an open source Python library that's widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray , and a large library of functions that operate efficiently on these data structures.\nIts ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries.\nNumPy arrays provide a significant speed advantage over traditional lists. This is because NumPy is built in C and uses optimized, pre-compiled code for numerical operations. This allows for vectorization, which means operations are applied to all elements in an array without the need for explicit loops in Python.\n\n##2.Compare and contrast np.mean() and np.average() functions in NumPy. 

In [3]:
import numpy as np
arr = np.array([1, 2, 3])
print("First array:\n",arr) 
arr1 = np.array([4, 5, 6])
print("Second array:\n",arr1) 
arr2 = np.vstack((arr, arr1))
print("Stacked array:\n",arr2) 

First array:
 [1 2 3]
Second array:
 [4 5 6]
Stacked array:
 [[1 2 3]
 [4 5 6]]


In [6]:
import numpy as geek 
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)   
# Stacking the two arrays horizontally 
out_arr = geek.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [ ]:
"""#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various 
array dimensions.
Ans

flip() you can flip the NumPy array ndarray vertically (up-down) or horizontally (left-right). There are also numpy. flipud() specialized for vertical flipping and numpy. fliplr() specialized for horizontal flipping.
"""

In [ ]:
"""
9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

split() is a function that divides an array into equal parts along a specified axis. The code imports NumPy creates an array of numbers (0-5), and then splits it in half (horizontally) using np. split() . The output shows the original array and the two resulting sub-arrays, each containing 3 elements
"""
"""
10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array 
operations?

Ans. Broadcasting provides a means for vectorizing the array operations so that looping would take place in C. It is a mechanism used by Numpy when it has to perform arithmetic operations on arrays with different shapes. 
Usual numpy broadcasting operations on two arrays are done on an element-by-element basis.
"""


In [7]:
# Practical questions
#1.. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
arr=np.random.randint(1,5,size=(3,3))
print (arr)

[[4 4 4]
 [4 2 4]
 [2 1 4]]


In [8]:
arr.reshape(3,3)

array([[4, 4, 4],
       [4, 2, 4],
       [2, 1, 4]], dtype=int32)

In [9]:
#2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a.reshape(2,5))
print(a.reshape(5,2))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [10]:
#3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np
x = np.ones((4, 4))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

Original array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5
np.arange(10, 60,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [13]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
#(uppercase, lowercase, title case, etc.) to each element


In [2]:
import numpy as np
x = np.array(['python', 'numpy', 'pandas'])
print("Original Array:")
print(x)

capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case) 

Original Array:
['python' 'numpy' 'pandas']

Capitalized:  ['Python' 'Numpy' 'Pandas']
Lowered:  ['python' 'numpy' 'pandas']
Uppered:  ['PYTHON' 'NUMPY' 'PANDAS']
Swapcased:  ['PYTHON' 'NUMPY' 'PANDAS']
Titlecased:  ['Python' 'Numpy' 'Pandas']


In [3]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
x = np.array(['python exercises', 'Assignment', 'program'])
print("Original Array:")
print(x)
r = np.char.join(" ", x)
print(r) 

Original Array:
['python exercises' 'Assignment' 'program']
['p y t h o n   e x e r c i s e s' 'A s s i g n m e n t' 'p r o g r a m']


In [8]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
a = np.array([ 20, 30, 40, 50])
b=np.array([ 0, 1, 2, 3])
c=a+b
print("The Addtion is ",c)
c=a-b
print("The subtraction is" , c)
c=a*b
print("The Multiplication is ", c)
c=a/b
print("The Division is ",c)

The Addtion is  [20 31 42 53]
The subtraction is [20 29 38 47]
The Multiplication is  [  0  30  80 150]
The Division is  [        inf 30.         20.         16.66666667]


C:\Users\rvss_\AppData\Local\Temp\ipykernel_4716\1976368685.py:11: RuntimeWarning: divide by zero encountered in divide
  c=a/b


In [10]:

#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x) 
x.diagonal()

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


array([1, 2, 3, 4, 5])

In [ ]:
#9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
#this array.

import random
p = [random.randint(1, 1000) for _ in range(100)]
flag = 0
for num in p:
    if num<2:
      flag = 1
    else:
      for i in range(2,int((num/2)+1)):
        if num%i==0:
          flag = 1
          break
    if flag == 1:
      print('Not Prime')
    else:
      print("Prime")

In [ ]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages
